export const userSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    first_name: { type: "string" },
    last_name: { type: "string" },
    phone: { type: "string" },
    dob: { type: "string" },
    email: { type: "string" },
    id: { type: "string" },
    created_at: { type: "string" },
    address: {
      type: "object",
      additonalProperties: false,
      properties: {
        street: { type: "string" },
        house_number: { type: "null" },
        city: { type: "string" },
        state: { type: "string" },
        country: { type: "string" },
        postal_code: { type: "string" },
      },
      required: ["street", "city", "state", "country", "postal_code"],
    },
  },
  required: [
    "first_name",
    "last_name",
    "phone",
    "dob",
    "email",
    "id",
    "created_at",
    "address",
  ],
};
